In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
iris=load_iris()
data=iris.data
features=iris.feature_names
target=iris.target_names

In [3]:
dataset=pd.DataFrame(data=data,columns=features)
dataset.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
from sklearn.model_selection import train_test_split

In [7]:
dataset.corr()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000

In [24]:
y=dataset["petal width (cm)"]
x=dataset[["sepal length (cm)","petal length (cm)"]]

In [61]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [62]:
from sklearn.linear_model import LinearRegression

In [68]:
reg=LinearRegression()
reg.fit(xtrain,ytrain)

LinearRegression()

In [69]:
ypred=reg.predict(xtest)

In [71]:
df_pred=pd.DataFrame({"Actual Value ":ytest,"Predicted Value ":ypred})
df_pred

Actual Value   Predicted Value 
149            1.8          1.784623
82             1.2          1.263167
56             1.6          1.583011
2              0.2          0.190001
47             0.2          0.240404
64             1.3          1.144027
55             1.3          1.533516
59             1.4          1.301650
76             1.4          1.594931
81             1.0          1.194430
88             1.3          1.363973
43             0.6          0.302727
38             0.2          0.209243
111            1.9          1.840532
113            2.0          1.753461
33             0.2          0.182679
39             0.2          0.252324
72             1.5          1.670989
126            1.8          1.633414
121            2.0          1.715886
49             0.2          0.214749
96             1.3          1.401548
71             1.3          1.287914
86             1.5          1.557355
127            1.8          1.683817
104            2.2          2.054064
138            1.8          1.646242
9              0.1          0.265152
74             1.3          1.400640
29             0.2          0.321969

In [67]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

mse = mean_squared_error(ytest,ypred) # A lower Mean Square Error (MSE) indicates better accuracy.
mae = mean_absolute_error(ytest,ypred) # neglects sign of mean of error. Only meant with the absolute value
rmse = np.sqrt(mse) # Root Mean Square Error give value in same unit

print("Mean Absolute Error : ",mae)
print("Mean Squared Error : ",mse)
print("Root Mean Squared Error : ",rmse)

Mean Absolute Error :  0.11267802634244568
Mean Squared Error :  0.019762494862835225
Root Mean Squared Error :  0.14057914092366344


# Linear Regression Multiple Variables

In [13]:
df=pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

# Pre-processing

In [18]:
df["bedrooms"].mode()[0]

3.0

In [21]:
df["bedrooms"]=df["bedrooms"].fillna(df["bedrooms"].mode()[0])

In [22]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

# Training Linear Regression Model

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
model=LinearRegression()

***Data Distribution***

In [26]:
y=df["price"]
x=df[["area","bedrooms","age"]]

In [27]:
model.fit(x,y)

LinearRegression()

In [28]:
model.coef_

array([  119.67905405, 13097.24903475, -4207.28764479])

In [29]:
model.intercept_

256461.14864864887

In [33]:
ypred=model.predict([[3000,3,40]])
ypred

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([486498.55212355])

In [40]:
ypred=model.predict([[2500,4,5]])
ypred

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([587011.34169884])

# Candidate Selection model

In [21]:
data=pd.read_csv("exe2_hiring.csv")
data.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [4]:
data["experience"]=data["experience"].fillna("one")

In [5]:
from word2number import w2n

In [6]:
data["experience"]=data["experience"].apply(w2n.word_to_num)

In [7]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           1                    8.0                           9      50000
1           1                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [8]:
data["test_score(out of 10)"]=data["test_score(out of 10)"].fillna(data["test_score(out of 10)"].mode()[0])

In [9]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           1                    8.0                           9      50000
1           1                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [10]:
y=data["salary($)"]
x=data[["experience","test_score(out of 10)","interview_score(out of 10)"]]

In [12]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [13]:
model.fit(x,y)

LinearRegression()

# Questions

***2yrs experience, 9 test score, 6 interview score***

In [15]:
result=model.predict([[2,9,6]])
result

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([51812.29680823])

***12yrs experience, 10 test score, 10 interview score***

In [17]:
result=model.predict([[12,10,10]])
result

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([95447.82955405])