In [1]:
import numpy as np

# Copy

**Creates copy of an array. Changings do not effect the copied array.**

In [2]:
arr1=np.array([2,6,8,9])

arrCpy=arr1.copy()

arrCpy

array([2, 6, 8, 9])

In [3]:
# changing effects
arr1[2]=10
print(arr1)
print(arrCpy)

[ 2  6 10  9]
[2 6 8 9]


***
# View

**Creates copy of an array. Changings do not effect the copied array.**

In [4]:
arr=np.array([1,2,5,7])

arrVi=arr.view()
print(arr)
print(arrVi)

[1 2 5 7]
[1 2 5 7]


In [5]:
# effect
arrVi[1]=10 #changes this index's value of both array
print(arr)
print(arrVi)

[ 1 10  5  7]
[ 1 10  5  7]


***