In [1]:
import numpy as np

# Insert

**insert() : It accepts three arguments : i) array_name. (ii) array's index(can be multiple indices) for value insertion. (iii)value.**

***Note :*** **It only accepts non-floating numbers.**

In [2]:
var = np.array([2,4,6,8])

print(var)

[2 4 6 8]


***Insertion on only one index***

In [3]:
np.insert(var,3,7)

array([2, 4, 6, 7, 8])

***Insertion on multiple indices***

In [4]:
np.insert(var,[1,4],9)

array([2, 9, 4, 6, 8, 9])

***
**2D insertion**

**insertion on 0 axis**

In [5]:
var2=np.array([[2,4,6],[1,3,5]])

np.insert(var2,1,[9,7,6],axis=0)#makes 9,7,6 as new column and insert it as 1 - column

array([[2, 4, 6],
       [9, 7, 6],
       [1, 3, 5]])

**insertion on 1 axis**

In [6]:
np.insert(var2,1,[5,10],axis=1)

array([[ 2,  5,  4,  6],
       [ 1, 10,  3,  5]])

# Append
**Works as insert but appends values at the end and accepts floating values**

***
# Deletion

**delete() : It accepts two arguments : i) array_name. (ii) array's index(can be multiple indices) for value deletion.**

# Handling 1D

In [7]:
arr=np.array([8,2,4,1])

**working with single value**

In [13]:
delt=np.delete(arr,(2))
print(arr)
print(delt)

[8 2 4 1]
[8 2 1]


**working with multiple values**

In [14]:
delt=np.delete(arr,(0,3))
print(arr)
print(delt)

[8 2 4 1]
[2 4]


***
# Handling 2

**In case of 2D whole row or column will be deleted.**

In [27]:
arr2=np.array([[2,1,5,8],[9,7,6,4]])
valDel=np.delete(arr2,[1],axis=1)
print(valDel)


[[2 5 8]
 [9 6 4]]
