In [1]:
import numpy as np

# Join
***

# 1-D Joining

In [18]:
arr=np.array([[1,2,4,5]])

arr1=np.array([[3,6,7,8]])

np.concatenate((arr,arr1),axis=1)

array([[1, 2, 4, 5, 3, 6, 7, 8]])

***
# 2-D joining

In [17]:
var=np.array([[2,1,4,5],[6,9,8,7]])

var1=np.array([[7,8,0,1],[7,1,9,0]])

print(var)
print()
print(var1)
np.concatenate((var,var1),axis=0)

[[2 1 4 5]
 [6 9 8 7]]

[[7 8 0 1]
 [7 1 9 0]]


array([[2, 1, 4, 5],
       [6, 9, 8, 7],
       [7, 8, 0, 1],
       [7, 1, 9, 0]])

***
# Stack

**This method allows us to join matrix horizontally, vertically and height wise.**

In [4]:
var=np.array([2,1,4,5])

var1=np.array([7,8,0,1])

print(var)
print()
print(var1)
print()
print("Adding data horizontally :\n",np.hstack((var,var1)))# joins next array as column.
print()
print("Adding data vertically :\n",np.vstack((var,var1)))#joins next array below first array.
print()
print("Adding data height wise :\n",np.dstack((var,var1)))#joins each array's index value with its corresponding index of next array.

[2 1 4 5]

[7 8 0 1]

Adding data horizontally :
 [2 1 4 5 7 8 0 1]

Adding data vertically :
 [[2 1 4 5]
 [7 8 0 1]]

Adding data height wise :
 [[[2 7]
  [1 8]
  [4 0]
  [5 1]]]


***
# Split

***
# Spliting 1-D

In [5]:
arr=np.array([2,1,4,5,7,8,0,1])

print(arr)
print()
sp_arr=np.array_split(arr,2)

for i in sp_arr:
    for j in i:
        print(j)
    print()

[2 1 4 5 7 8 0 1]

2
1
4
5

7
8
0
1



***
# Spliting 2-D

In [6]:
arr2=np.array([[2,1,4,5],[7,8,0,1]])

In [7]:
print(arr2)
print()
arr2_split=np.array_split(arr2,2,axis=1)
print(arr2_split)

[[2 1 4 5]
 [7 8 0 1]]

[array([[2, 1],
       [7, 8]]), array([[4, 5],
       [0, 1]])]


***