In [1]:
import numpy as np

# Matrix
**Creation of Matrix**

In [2]:
var= np.matrix([[1,2],[5,6]])
var1= np.matrix([[6,4],[9,5]])

# ***Matrix Functions***

***
# Dot product
**Also works on the basis of Broadcasting**

In [3]:
print(var)
print()
print(var1)
print()
print(var.dot(var1))

# print(var@var1)

[[1 2]
 [5 6]]

[[6 4]
 [9 5]]

[[24 14]
 [84 50]]


***
# Transpose

***Handling 1D matrix***

In [4]:
mat=np.matrix([[1,2,4],[2,6,8]])

mat

matrix([[1, 2, 4],
        [2, 6, 8]])

In [5]:
np.transpose(mat)

matrix([[1, 2],
        [2, 6],
        [4, 8]])

In [6]:
mat1=np.matrix([[1,2,4],[2,6,8],[7,8,2]])

print(mat1)

[[1 2 4]
 [2 6 8]
 [7 8 2]]


In [7]:
np.transpose(mat1)#mat1.T

matrix([[1, 2, 7],
        [2, 6, 8],
        [4, 8, 2]])

***
# Swapaxes

In [8]:
# Its syntax is : np.swapaxes(mat_name,0,1)
#works as transpose()

np.swapaxes(mat1,0,1)

matrix([[1, 2, 7],
        [2, 6, 8],
        [4, 8, 2]])

***
# Inverse

In [9]:
varInv=np.array([[1,2],[3,4]])
print(varInv)
print()
print(np.linalg.inv(varInv))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


***
# Power

In [10]:
#np.linalg.matrix_power(mat_name,pow)

***
# Determinate

In [15]:
matDet=np.matrix([[1,2,3],[3,4,3],[1,2,3]])

print(np.linalg.det(matDet))

0.0


***