In [1]:
import numpy as np

In [2]:
arr=np.array([1,8,2,8,7,1,5,2,9])

# Searching

**where**:***returns index of particular value in an array.***

In [5]:
val=np.where(arr==2)#works as filter in js
val

(array([2, 7], dtype=int64),)

In [6]:
gr=np.where(arr>5)#works as filter in js
gr

(array([1, 3, 4, 8], dtype=int64),)

***
# Sorting

In [21]:
arr=np.array([[1,8,2,18,7],[11,5,12,9,3]])
print(arr)
print()
print(np.sort(arr))

[[ 1  8  2 18  7]
 [11  5 12  9  3]]

[[ 1  2  7  8 18]
 [ 3  5  9 11 12]]


***
# Filtering an array based on any requirement

In [23]:
arrFiltr=np.array([2,1,8,12,9,11])
rquir=[False,False,True,True,False,True]#give true on those corresponding index which value's required

print(arrFiltr[rquir])

[ 8 12 11]


***
# Shuffle

**Used to mix up data randomly.Works with numpy's random().**

In [29]:
arrData=np.array([1,2,6,8,7])
print(arrData)
print()
np.random.shuffle(arrData)
print(arrData)

[1 2 6 8 7]

[7 2 6 1 8]


***
# Unique

**Used to get unique values and their indexes within an array.**

**It has three parameters : array, return_index(if needed) and return_counts(if needed).**

In [39]:
arrRp=np.array([1,2,4,5,1,5,2,4])

r=np.unique(arrRp,return_index=True,return_counts=True)
r

(array([1, 2, 4, 5]),
 array([0, 1, 2, 3], dtype=int64),
 array([2, 2, 2, 2], dtype=int64))

***
# Ravel

**It also accepts order: C to change matrix row wise and F to change matrix column wise.**

In [43]:
arrRa=np.array([[1,8,2,18,7],[11,5,12,9,3]])
rvalRow=np.ravel(arrRa,order="C")#row wise shape changing
rvalCol=np.ravel(arrRa,order="F")#column wise shape changing
print(rvalRow)
print()
print(rvalCol)

[ 1  8  2 18  7 11  5 12  9  3]

[ 1 11  8  5  2 12 18  9  7  3]
