In [1]:
import numpy as np

**1.Getting minimum and maximum values within an Array**

In [9]:
arr=np.array([80,0,170,1])
print("Maximum val is ",np.max(arr))
print("Minimum val is ",np.min(arr))

Maximum val is  170
Minimum val is  0


***
**2.Getting index of max and min values within array**

In [10]:
print("Maximum val is ",np.max(arr),". Its index is ",np.argmax(arr))
print("Minimum val is ",np.min(arr),". Its index is ",np.argmin(arr))

Maximum val is  170 . Its index is  2
Minimum val is  0 . Its index is  1


***
**3.Finding sqroot of any array**

In [14]:
val=np.array([[4,9,16,25],[36,49,64,81]])
np.sqrt(val)

array([[2., 3., 4., 5.],
       [6., 7., 8., 9.]])

***
**4.Finding sin/cos of any array**

In [20]:
trgVal=np.array([1,2,3])
 
print(np.sin(trgVal))
print(np.cos(trgVal))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


***
**5.Finding Cumulative Sum of an array**

In [24]:
cumSum=np.array([[2,5,8,7],[1,8,6,9]])

np.cumsum(cumSum)

array([ 2,  7, 15, 22, 23, 31, 37, 46])

***